#!/bin/bash

SCRIPT_HOME="."
function getSpaces(){
    tabs 4
    tabs=""

    for (( i=0; i<$1; i++ )); do
        tabs="${tabs}\t"
    done
    
    if [[ "$1" > 0 ]]; then
        echo -e ${tabs}
    fi 
}

function formatJson(){
    output=""
    bracket_count=0
    
    for (( i=0; i<${#1}; i++ )); do
        current_char="${1:$i:1}"
        spaces="$(getSpaces $bracket_count)"
        
        if [[ "$current_char" = "{" || "$current_char" = "," || "$current_char" = "[" ]]; then
            output="$output$current_char"
            echo "${spaces}${output}"
            output=""
            if [[ "$current_char" = "{" || "$current_char" = "[" ]]; then 
                ((bracket_count++))
            fi
        elif [[ "$current_char" = "}" || "$current_char" = "]" ]]; then
            echo "${spaces}${output}"
            output="$current_char"
            ((bracket_count--))
        else
            output="$output$current_char"
        fi
        
    done
}
