#!/bin/bash

SCRIPT_HOME="."
source ${SCRIPT_HOME}/setupEnv

if [ -z "$1" ]; then
    echo "please give a light to switch"
    exit 0
fi

curl -X "PUT" --data "{\"on\": false}" ${URL}/api/${USER}/lights/$1/state
echo -e "\n"
